### ISSUE TITLE
multiple screens

### ISSUE THREAD

**Issue by turkin** [Bodmer/TFT_S6D02A1#2]
Can it handle two or more screens at the same time? with diferent cs pins?

**Comment by Bodmer** [comment]
Yes, but the chip selects must be managed by the sketch depending on which screen you communicate with. Set the chip select low to communicate with one display. Set both chip selects to write identical things to the two displays and also during init or begin.

In the setup file set the chip select to -1.

**Comment by turkin** [comment]
And how i declare tft1_cs to pin x and tft2_cs to pin y?

**Comment by turkin** [comment]
I create only one tft and i select low only to the cs of the screen i want to print?

**Comment by turkin** [comment]
Thanks! It works!!

**Comment by Bodmer** [comment]
Great!
